//! Fixture-backed tests for resolution-aware Q' reading.
//!
//! Fixtures are generated by `scripts/make_streamflow_fixtures.py` (run under
//! DDR's uv venv) and checked into tests/fixtures/. Deterministic values:
//!   qr_daily.ic  : 4 divides [101..104] x 10 days,   Qr[j, t] = (j+1)*100  + t
//!   qr_hourly.ic : 4 divides [101..104] x 240 hours, Qr[j, h] = (j+1)*1000 + h
//! Both axes start 1981-01-01.

use chrono::NaiveDate;

use ddrs::data::dates::{Frequency, RhoWindow, TimeAxis};
use ddrs::data::ids::Comid;
use ddrs::data::store::{StreamflowSource, StreamflowStore};
use ddrs::data::TestWindow;

fn fixture(name: &str) -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

fn d(y: i32, m: u32, day: u32) -> NaiveDate {
    NaiveDate::from_ymd_opt(y, m, day).unwrap()
}

const COMIDS: [Comid; 4] = [Comid(101), Comid(102), Comid(103), Comid(104)];

#[test]
fn hourly_store_opens_with_hourly_resolution() {
    let s = StreamflowStore::open(fixture("qr_hourly.ic")).expect("open");
    assert_eq!(s.resolution, Frequency::Hourly);
    assert_eq!(s.time_start, d(1981, 1, 1));
    assert_eq!(s.n_time, 240);
    assert_eq!(s.index.len(), 4);
    assert_eq!(s.qr_units().as_deref(), Some("m^3/s"));
}

#[test]
fn daily_store_opens_with_daily_resolution() {
    let s = StreamflowStore::open(fixture("qr_daily.ic")).expect("open");
    assert_eq!(s.resolution, Frequency::Daily);
    assert_eq!(s.time_start, d(1981, 1, 1));
    assert_eq!(s.n_time, 10);
}

#[test]
fn minutes_axis_is_rejected_at_open() {
    let err = StreamflowSource::open(fixture("qr_minutes.ic")).unwrap_err();
    assert!(
        err.to_string().contains("unsupported time units"),
        "got: {err}"
    );
}

#[test]
fn hourly_read_window_slices_natively() {
    let s = StreamflowStore::open(fixture("qr_hourly.ic")).expect("open");
    // Window: days [2, 6) of the axis → hours [48, 120); n_hourly = 3*24 = 72.
    let w = RhoWindow {
        start_day_idx: 2,
        rho_days: 4,
        window_start: d(1981, 1, 3),
    };
    let q = s.read_window(&w, &COMIDS).expect("read_window");
    assert_eq!(q.shape(), &[72, 4]);
    for h in 0..72 {
        for j in 0..4 {
            let expect = (j as f32 + 1.0) * 1000.0 + (48 + h) as f32;
            assert_eq!(q[(h, j)], expect, "mismatch at hour {h}, divide {j}");
        }
    }
}

#[test]
fn hourly_read_window_daily_is_24h_mean() {
    let s = StreamflowStore::open(fixture("qr_hourly.ic")).expect("open");
    let q = s
        .read_window_daily(d(1981, 1, 3), 4, &COMIDS)
        .expect("read_window_daily");
    assert_eq!(q.shape(), &[4, 4]);
    // Day d of the window covers hours 48+24d .. 48+24d+24; the mean of a
    // 24-term arithmetic ramp k..k+23 is k + 11.5.
    for day in 0..4 {
        for j in 0..4 {
            let expect = (j as f32 + 1.0) * 1000.0 + (48 + 24 * day) as f32 + 11.5;
            assert_eq!(q[(day, j)], expect, "mismatch at day {day}, divide {j}");
        }
    }
}

#[test]
fn hourly_read_test_window_is_contiguous() {
    let s = StreamflowStore::open(fixture("qr_hourly.ic")).expect("open");
    let axis = TimeAxis::new(d(1981, 1, 1), d(1981, 1, 10));
    let w = TestWindow::new(&axis, 2, 4); // hours [48, 144), no trailing trim
    let q = s.read_test_window(&w, &COMIDS).expect("read_test_window");
    assert_eq!(q.shape(), &[96, 4]);
    assert_eq!(q[(0, 0)], 1000.0 + 48.0);
    assert_eq!(q[(95, 3)], 4000.0 + 143.0);
}

#[test]
fn hourly_missing_comid_gets_fill() {
    let s = StreamflowStore::open(fixture("qr_hourly.ic")).expect("open");
    let w = RhoWindow {
        start_day_idx: 0,
        rho_days: 2,
        window_start: d(1981, 1, 1),
    };
    let q = s
        .read_window(&w, &[Comid(101), Comid(999)])
        .expect("read_window");
    assert_eq!(q.shape(), &[24, 2]);
    assert_eq!(q[(5, 0)], 1000.0 + 5.0);
    assert_eq!(q[(5, 1)], 0.001, "missing COMID must fill with 0.001");
}

#[test]
fn hourly_out_of_range_windows_hard_error() {
    let s = StreamflowStore::open(fixture("qr_hourly.ic")).expect("open");
    // Before store start.
    let before = RhoWindow {
        start_day_idx: 0,
        rho_days: 2,
        window_start: d(1980, 12, 1),
    };
    let err = s.read_window(&before, &COMIDS).unwrap_err();
    assert!(err.to_string().contains("before store start"), "got: {err}");
    // Past store end (store holds 10 days).
    let past = RhoWindow {
        start_day_idx: 8,
        rho_days: 5,
        window_start: d(1981, 1, 9),
    };
    assert!(s.read_window(&past, &COMIDS).is_err());
}

#[test]
fn streamflow_source_reports_resolution() {
    let daily = StreamflowSource::open(fixture("qr_daily.ic")).expect("open daily");
    assert_eq!(daily.resolution(), Frequency::Daily);
    let hourly = StreamflowSource::open(fixture("qr_hourly.ic")).expect("open hourly");
    assert_eq!(hourly.resolution(), Frequency::Hourly);
}

#[test]
fn daily_fixture_read_window_keeps_repeat24_semantics() {
    // Pins the daily path: values repeat 24x per day with the trailing-day trim.
    let s = StreamflowStore::open(fixture("qr_daily.ic")).expect("open");
    let w = RhoWindow {
        start_day_idx: 2,
        rho_days: 4,
        window_start: d(1981, 1, 3),
    };
    let q = s.read_window(&w, &COMIDS).expect("read_window");
    assert_eq!(q.shape(), &[72, 4]);
    for h in 0..72 {
        for j in 0..4 {
            let expect = (j as f32 + 1.0) * 100.0 + (2 + h / 24) as f32;
            assert_eq!(q[(h, j)], expect, "mismatch at hour {h}, divide {j}");
        }
    }
}
